### ISSUE TITLE
A simple question

### ISSUE THREAD

**Issue by Ivory433** [cl2089/etherscan-contract-crawler#10] opened 2023-04-23 12:37 UTC
First of all, this is an awesome project, but I am wondering how to bypass the cloudflare protection on the etherscan page using you script?

**Comment by Emmanuelwh** [comment] 2023-05-30 07:44
Excuse me, Do you slove it? I met the same problem

**Comment by cassc** [comment] 2023-06-14 07:33
Duplicate of https://github.com/cassc/etherscan-contract-crawler/issues/11

**Closed as completed by cassc** 2023-06-14 07:33 UTC
